language: java
dist: trusty

cache:
  directories:
    - $HOME/.gradle

before_script:
  - chmod +x deploy_bintray.sh

script:
  - ./gradlew test --info

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - ./deploy_bintray.sh
